development:
  bucket: Creator_Dev
  access_key_id: AKIAJLOXM6Z34V4OA7PQ
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read

production:
  bucket: Creator_Pro
  max_file_size: 10485760
  acl: public-read
